#!/usr/bin/env python3
"""
Setup wizard for Spotify API credentials
"""

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.markdown import Markdown
import os
from pathlib import Path

console = Console()


def show_setup_guide():
    """Show instructions for getting Spotify credentials"""
    guide = """
# 🎵 Spotify API Setup Guide

## Step 1: Go to Spotify Developer Dashboard
Visit: https://developer.spotify.com/dashboard

## Step 2: Log In
Use your Spotify account (free or premium)

## Step 3: Create an App
1. Click **"Create App"**
2. Fill in the form:
   - **App name:** Playlist Farmer
   - **App description:** Tool to search and analyze public playlists
   - **Website:** http://localhost (or leave blank)
   - **Redirect URI:** http://localhost:8888/callback

## Step 4: Select API
- ✅ Check **"Web API"**

## Step 5: Accept Terms
- ✅ Accept Spotify's Developer Terms of Service

## Step 6: Get Credentials
1. Click on your new app
2. Click **"Settings"** (top right)
3. You'll see:
   - **Client ID** - copy this
   - **Client Secret** - click "View client secret" and copy

## Step 7: Enter Them Below!
"""
    console.print(Markdown(guide))


def get_config_file_path():
    """Get the path to the config file"""
    # Try to use user's home directory
    home = Path.home()
    config_dir = home / ".playlist-farm"
    config_dir.mkdir(exist_ok=True)
    return config_dir / "config.env"


def save_credentials(client_id: str, client_secret: str):
    """Save credentials to config file"""
    config_file = get_config_file_path()

    with open(config_file, 'w') as f:
        f.write(f"# Spotify API Credentials\n")
        f.write(f"# Generated by spotify-farmer setup\n\n")
        f.write(f"SPOTIFY_CLIENT_ID={client_id}\n")
        f.write(f"SPOTIFY_CLIENT_SECRET={client_secret}\n")

    # Make file readable only by user
    os.chmod(config_file, 0o600)

    return config_file


def load_credentials():
    """Load credentials from config file"""
    config_file = get_config_file_path()

    if not config_file.exists():
        return None, None

    client_id = None
    client_secret = None

    with open(config_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('SPOTIFY_CLIENT_ID='):
                client_id = line.split('=', 1)[1]
            elif line.startswith('SPOTIFY_CLIENT_SECRET='):
                client_secret = line.split('=', 1)[1]

    return client_id, client_secret


def main():
    """Run the setup wizard"""
    console.print(Panel.fit(
        "[bold green]🎵 Spotify Playlist Farmer Setup[/bold green]\n"
        "[dim]Configure your API credentials[/dim]",
        border_style="cyan"
    ))

    # Check if credentials already exist
    existing_id, existing_secret = load_credentials()

    if existing_id and existing_secret:
        console.print("\n[green]✓[/green] Existing credentials found!")
        console.print(f"[dim]Client ID: {existing_id[:20]}...[/dim]")

        if not Confirm.ask("\nDo you want to update them?", default=False):
            console.print("\n[green]Setup cancelled. Existing credentials unchanged.[/green]")
            return

    # Show guide
    console.print("\n")
    if Confirm.ask("Do you need help getting Spotify API credentials?", default=True):
        show_setup_guide()
        console.print("\n[dim]Press Enter when ready...[/dim]")
        input()

    # Get credentials
    console.print(Panel(
        "Enter your Spotify API credentials\n"
        "[dim]These will be saved securely to your home directory[/dim]",
        title="🔑 Credentials",
        border_style="yellow"
    ))

    client_id = Prompt.ask("\n[cyan]Client ID[/cyan]")
    client_secret = Prompt.ask("[cyan]Client Secret[/cyan]", password=True)

    if not client_id or not client_secret:
        console.print("\n[red]❌ Both Client ID and Secret are required![/red]")
        return

    # Save credentials
    config_file = save_credentials(client_id, client_secret)

    console.print(f"\n[green]✅ Credentials saved![/green]")
    console.print(f"[dim]Location: {config_file}[/dim]")

    console.print(Panel.fit(
        "[bold green]Setup Complete![/bold green]\n\n"
        "Your credentials are now saved and will be used automatically.\n"
        "You can now run:\n\n"
        "  [cyan]spotify-farmer[/cyan]     - Beautiful CLI\n"
        "  [cyan]spotify-farmer-tui[/cyan] - Terminal UI\n\n"
        "To update credentials later, run [cyan]spotify-farmer-setup[/cyan] again.",
        border_style="green"
    ))


if __name__ == "__main__":
    main()
